name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      # OIDC_AUDIENCE: 'jfrog-github'
      # OIDC_PROVIDER: 'guy-github'
      PLATFORM_REPO: 'guy-npm-dev-npm'
      JFROG_CLI_LOG_LEVEL: DEBUG
      JF_USER: guyyb@jfrog.com
      JF_ACCESS_TOKEN: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiI5RDkzSk1Bbzk3ekpIazdjZDluWlNZNEgyWFE1amtzSTB0ZTNoM0h4WEpJIn0.eyJzdWIiOiJqZmFjQDAxaHJwZG5zeGNlMzMzMW1zcXl4NzQwbngxL3VzZXJzL2d1eXliQGpmcm9nLmNvbSIsInNjcCI6ImFwcGxpZWQtcGVybWlzc2lvbnMvdXNlciIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDFocnBkbnN4Y2UzMzMxbXNxeXg3NDBueDEiLCJpYXQiOjE3MTAyNTQwNDMsImp0aSI6IjZmOGE1NDM1LTYyMzAtNDJlOS1iZjI3LTdmNWI2OTQyMWJiMCJ9.Dqth3m8-PW_L0MTz-NhNgjRbIieyIqMw1meyKYrQfxMllk6uyhs8cD6Ydl180wQG6DCBSnaaBVghXX5yfVovAO5is_kFjTsLW2TgAIh3KdBrjgkvx2cRzSnOOpAlies56q3JKYiucjwkomQbnOfwX7W7JVPO2REJn2s4tg_0VX8NcEyufn1v6nYtQRZQEADujKs-m_cwdqoeK3Q6Cxyoexmczke1nQuj-hPGDlJizpgOQoa2klcNnLF9HKkL1NYVUZJY9C5DpnrpLzaa-zBCBkJvsD_zE1DBQ2RQTy59CDzYZp4rgQ8vTB0GUlkq-RkfLNWpoUyigTr83olC1_6J1g
      # JF_ACCESS_TOKEN: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiI5RDkzSk1Bbzk3ekpIazdjZDluWlNZNEgyWFE1amtzSTB0ZTNoM0h4WEpJIn0.eyJzdWIiOiJqZmFjQDAxaHJwZG5zeGNlMzMzMW1zcXl4NzQwbngxL3VzZXJzL2d1eXliQGpmcm9nLmNvbSIsInNjcCI6ImFwcGxpZWQtcGVybWlzc2lvbnMvdXNlciIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDFocnBkbnN4Y2UzMzMxbXNxeXg3NDBueDEiLCJpYXQiOjE3MTAyNDgyODEsImp0aSI6IjY4MDFiMTcxLWVlZjMtNDk4MC05YTk1LThmOGJlYjNjYzExYiJ9.SgoLc5A64fOxXXCVA18UiCNGAsTERGhvSO8fckBbD_i47SGtP4QDXwNSHxOKLLOWm_ejYHZxG3lK1DiQ5S-sPtU1U8jrX3FmeNKmQepXEaSqGo_QrskZv0MgEXCFUfiUW0ncNmUhfZeOdQGULKZVpSoS6DLjrTbDu5bEUzYow60lPK2AHnPQD3qtPWJgOnRQ4_Z_yEC3cP3RRUv7Ka0z3PxFmCiKDU0bTIfSKI0bBY2CiBsnxXF5uHtGwNvC_rQdUAilkSNOw_9GckaZsa2Hcd3qfaVOCwEUZMKPDI1kLRfLLsqa-ElW8ta1vRXKjaFZBO1JQLyCmVDbam-60_Ddmg
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
           JFROG_CLI_LOG_LEVEL: DEBUG
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}

       - name: Set CLI Config
         run: jf npm-config --global=true --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO
           
       - name: Install Dependencies
         run: jf npm install
           
       - name: Run tests
         run: npm test
         
       - name: Publish
         run: jf npm publish
         
       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt build-collect-env
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt build-publish
